name: 'setup-gpg'
description: 'Prepare to get following commits signed'

inputs:
    gpgPriv:
        description: 'GPG Private key'
        required: true
        default: ''
    gpgPassPhrase:
        description: 'GPG passphrase'
        required: false
        default: '""'

runs:
    using: composite
    steps:
        - name: Import and load GPG key
          uses: crazy-max/ghaction-import-gpg@cb9bde2e2525e640591a934b1fd28eef1dcaf5e5 # v6.2.0
          with:
              gpg_private_key: ${{ inputs.gpgPriv }}
              passphrase: ${{ inputs.gpgPassPhrase }}
              git_user_signingkey: true
              git_commit_gpgsign: true
