namespace GoogleProvider {
    export const Style = {
        Standard: {
            id: 0,
            label: 'Standard',
            style: '',
            urlStyle: ''
        },
        Silver: {
            id: 1,
            label: 'Silver',
            style:
                "[{'elementType':'geometry','stylers':[{'color':'#f5f5f5'}]},{'elementType':'labels.icon','stylers':[{'visibility':'off'}]},{'elementType':'labels.text.fill','stylers':[{'color':'#616161'}]},{'elementType':'labels.text.stroke','stylers':[{'color':'#f5f5f5'}]},{'featureType':'administrative.land_parcel','elementType':'labels.text.fill','stylers':[{'color':'#bdbdbd'}]},{'featureType':'poi','elementType':'geometry','stylers':[{'color':'#eeeeee'}]},{'featureType':'poi','elementType':'labels.text.fill','stylers':[{'color':'#757575'}]},{'featureType':'poi.park','elementType':'geometry','stylers':[{'color':'#e5e5e5'}]},{'featureType':'poi.park','elementType':'labels.text.fill','stylers':[{'color':'#9e9e9e'}]},{'featureType':'road','elementType':'geometry','stylers':[{'color':'#ffffff'}]},{'featureType':'road.arterial','elementType':'labels.text.fill','stylers':[{'color':'#757575'}]},{'featureType':'road.highway','elementType':'geometry','stylers':[{'color':'#dadada'}]},{'featureType':'road.highway','elementType':'labels.text.fill','stylers':[{'color':'#616161'}]},{'featureType':'road.local','elementType':'labels.text.fill','stylers':[{'color':'#9e9e9e'}]},{'featureType':'transit.line','elementType':'geometry','stylers':[{'color':'#e5e5e5'}]},{'featureType':'transit.station','elementType':'geometry','stylers':[{'color':'#eeeeee'}]},{'featureType':'water','elementType':'geometry','stylers':[{'color':'#c9c9c9'}]},{'featureType':'water','elementType':'labels.text.fill','stylers':[{'color':'#9e9e9e'}]}]",
            urlStyle:
                '&style=element:geometry%7Ccolor:0xf5f5f5&style=element:labels.icon%7Cvisibility:off&style=element:labels.text.fill%7Ccolor:0x616161&style=element:labels.text.stroke%7Ccolor:0xf5f5f5&style=feature:administrative.land_parcel%7Celement:labels.text.fill%7Ccolor:0xbdbdbd&style=feature:poi%7Celement:geometry%7Ccolor:0xeeeeee&style=feature:poi%7Celement:labels.text.fill%7Ccolor:0x757575&style=feature:poi.park%7Celement:geometry%7Ccolor:0xe5e5e5&style=feature:poi.park%7Celement:labels.text.fill%7Ccolor:0x9e9e9e&style=feature:road%7Celement:geometry%7Ccolor:0xffffff&style=feature:road.arterial%7Celement:labels.text.fill%7Ccolor:0x757575&style=feature:road.highway%7Celement:geometry%7Ccolor:0xdadada&style=feature:road.highway%7Celement:labels.text.fill%7Ccolor:0x616161&style=feature:road.local%7Celement:labels.text.fill%7Ccolor:0x9e9e9e&style=feature:transit.line%7Celement:geometry%7Ccolor:0xe5e5e5&style=feature:transit.station%7Celement:geometry%7Ccolor:0xeeeeee&style=feature:water%7Celement:geometry%7Ccolor:0xc9c9c9&style=feature:water%7Celement:labels.text.fill%7Ccolor:0x9e9e9e'
        },
        Retro: {
            id: 2,
            label: 'Retro',
            style:
                "[{'elementType':'geometry','stylers':[{'color':'#ebe3cd'}]},{'elementType':'labels.text.fill','stylers':[{'color':'#523735'}]},{'elementType':'labels.text.stroke','stylers':[{'color':'#f5f1e6'}]},{'featureType':'administrative','elementType':'geometry.stroke','stylers':[{'color':'#c9b2a6'}]},{'featureType':'administrative.land_parcel','elementType':'geometry.stroke','stylers':[{'color':'#dcd2be'}]},{'featureType':'administrative.land_parcel','elementType':'labels.text.fill','stylers':[{'color':'#ae9e90'}]},{'featureType':'landscape.natural','elementType':'geometry','stylers':[{'color':'#dfd2ae'}]},{'featureType':'poi','elementType':'geometry','stylers':[{'color':'#dfd2ae'}]},{'featureType':'poi','elementType':'labels.text.fill','stylers':[{'color':'#93817c'}]},{'featureType':'poi.park','elementType':'geometry.fill','stylers':[{'color':'#a5b076'}]},{'featureType':'poi.park','elementType':'labels.text.fill','stylers':[{'color':'#447530'}]},{'featureType':'road','elementType':'geometry','stylers':[{'color':'#f5f1e6'}]},{'featureType':'road.arterial','elementType':'geometry','stylers':[{'color':'#fdfcf8'}]},{'featureType':'road.highway','elementType':'geometry','stylers':[{'color':'#f8c967'}]},{'featureType':'road.highway','elementType':'geometry.stroke','stylers':[{'color':'#e9bc62'}]},{'featureType':'road.highway.controlled_access','elementType':'geometry','stylers':[{'color':'#e98d58'}]},{'featureType':'road.highway.controlled_access','elementType':'geometry.stroke','stylers':[{'color':'#db8555'}]},{'featureType':'road.local','elementType':'labels.text.fill','stylers':[{'color':'#806b63'}]},{'featureType':'transit.line','elementType':'geometry','stylers':[{'color':'#dfd2ae'}]},{'featureType':'transit.line','elementType':'labels.text.fill','stylers':[{'color':'#8f7d77'}]},{'featureType':'transit.line','elementType':'labels.text.stroke','stylers':[{'color':'#ebe3cd'}]},{'featureType':'transit.station','elementType':'geometry','stylers':[{'color':'#dfd2ae'}]},{'featureType':'water','elementType':'geometry.fill','stylers':[{'color':'#b9d3c2'}]},{'featureType':'water','elementType':'labels.text.fill','stylers':[{'color':'#92998d'}]}]",
            urlStyle:
                '&style=element:geometry%7Ccolor:0xebe3cd&style=element:labels.text.fill%7Ccolor:0x523735&style=element:labels.text.stroke%7Ccolor:0xf5f1e6&style=feature:administrative%7Celement:geometry.stroke%7Ccolor:0xc9b2a6&style=feature:administrative.land_parcel%7Celement:geometry.stroke%7Ccolor:0xdcd2be&style=feature:administrative.land_parcel%7Celement:labels.text.fill%7Ccolor:0xae9e90&style=feature:landscape.natural%7Celement:geometry%7Ccolor:0xdfd2ae&style=feature:poi%7Celement:geometry%7Ccolor:0xdfd2ae&style=feature:poi%7Celement:labels.text.fill%7Ccolor:0x93817c&style=feature:poi.park%7Celement:geometry.fill%7Ccolor:0xa5b076&style=feature:poi.park%7Celement:labels.text.fill%7Ccolor:0x447530&style=feature:road%7Celement:geometry%7Ccolor:0xf5f1e6&style=feature:road.arterial%7Celement:geometry%7Ccolor:0xfdfcf8&style=feature:road.highway%7Celement:geometry%7Ccolor:0xf8c967&style=feature:road.highway%7Celement:geometry.stroke%7Ccolor:0xe9bc62&style=feature:road.highway.controlled_access%7Celement:geometry%7Ccolor:0xe98d58&style=feature:road.highway.controlled_access%7Celement:geometry.stroke%7Ccolor:0xdb8555&style=feature:road.local%7Celement:labels.text.fill%7Ccolor:0x806b63&style=feature:transit.line%7Celement:geometry%7Ccolor:0xdfd2ae&style=feature:transit.line%7Celement:labels.text.fill%7Ccolor:0x8f7d77&style=feature:transit.line%7Celement:labels.text.stroke%7Ccolor:0xebe3cd&style=feature:transit.station%7Celement:geometry%7Ccolor:0xdfd2ae&style=feature:water%7Celement:geometry.fill%7Ccolor:0xb9d3c2&style=feature:water%7Celement:labels.text.fill%7Ccolor:0x92998d'
        },
        Dark: {
            id: 3,
            label: 'Dark',
            style:
                "[{'elementType':'geometry','stylers':[{'color':'#212121'}]},{'elementType':'labels.icon','stylers':[{'visibility':'off'}]},{'elementType':'labels.text.fill','stylers':[{'color':'#757575'}]},{'elementType':'labels.text.stroke','stylers':[{'color':'#212121'}]},{'featureType':'administrative','elementType':'geometry','stylers':[{'color':'#757575'}]},{'featureType':'administrative.country','elementType':'labels.text.fill','stylers':[{'color':'#9e9e9e'}]},{'featureType':'administrative.land_parcel','stylers':[{'visibility':'off'}]},{'featureType':'administrative.locality','elementType':'labels.text.fill','stylers':[{'color':'#bdbdbd'}]},{'featureType':'poi','elementType':'labels.text.fill','stylers':[{'color':'#757575'}]},{'featureType':'poi.park','elementType':'geometry','stylers':[{'color':'#181818'}]},{'featureType':'poi.park','elementType':'labels.text.fill','stylers':[{'color':'#616161'}]},{'featureType':'poi.park','elementType':'labels.text.stroke','stylers':[{'color':'#1b1b1b'}]},{'featureType':'road','elementType':'geometry.fill','stylers':[{'color':'#2c2c2c'}]},{'featureType':'road','elementType':'labels.text.fill','stylers':[{'color':'#8a8a8a'}]},{'featureType':'road.arterial','elementType':'geometry','stylers':[{'color':'#373737'}]},{'featureType':'road.highway','elementType':'geometry','stylers':[{'color':'#3c3c3c'}]},{'featureType':'road.highway.controlled_access','elementType':'geometry','stylers':[{'color':'#4e4e4e'}]},{'featureType':'road.local','elementType':'labels.text.fill','stylers':[{'color':'#616161'}]},{'featureType':'transit','elementType':'labels.text.fill','stylers':[{'color':'#757575'}]},{'featureType':'water','elementType':'geometry','stylers':[{'color':'#000000'}]},{'featureType':'water','elementType':'labels.text.fill','stylers':[{'color':'#3d3d3d'}]}]",
            urlStyle:
                '&style=element:geometry%7Ccolor:0x212121&style=element:labels.icon%7Cvisibility:off&style=element:labels.text.fill%7Ccolor:0x757575&style=element:labels.text.stroke%7Ccolor:0x212121&style=feature:administrative%7Celement:geometry%7Ccolor:0x757575&style=feature:administrative.country%7Celement:labels.text.fill%7Ccolor:0x9e9e9e&style=feature:administrative.land_parcel%7Cvisibility:off&style=feature:administrative.locality%7Celement:labels.text.fill%7Ccolor:0xbdbdbd&style=feature:poi%7Celement:labels.text.fill%7Ccolor:0x757575&style=feature:poi.park%7Celement:geometry%7Ccolor:0x181818&style=feature:poi.park%7Celement:labels.text.fill%7Ccolor:0x616161&style=feature:poi.park%7Celement:labels.text.stroke%7Ccolor:0x1b1b1b&style=feature:road%7Celement:geometry.fill%7Ccolor:0x2c2c2c&style=feature:road%7Celement:labels.text.fill%7Ccolor:0x8a8a8a&style=feature:road.arterial%7Celement:geometry%7Ccolor:0x373737&style=feature:road.highway%7Celement:geometry%7Ccolor:0x3c3c3c&style=feature:road.highway.controlled_access%7Celement:geometry%7Ccolor:0x4e4e4e&style=feature:road.local%7Celement:labels.text.fill%7Ccolor:0x616161&style=feature:transit%7Celement:labels.text.fill%7Ccolor:0x757575&style=feature:water%7Celement:geometry%7Ccolor:0x000000&style=feature:water%7Celement:labels.text.fill%7Ccolor:0x3d3d3d'
        },
        Night: {
            id: 4,
            label: 'Night',
            style:
                "[{'elementType':'geometry','stylers':[{'color':'#242f3e'}]},{'elementType':'labels.text.fill','stylers':[{'color':'#746855'}]},{'elementType':'labels.text.stroke','stylers':[{'color':'#242f3e'}]},{'featureType':'administrative.locality','elementType':'labels.text.fill','stylers':[{'color':'#d59563'}]},{'featureType':'poi','elementType':'labels.text.fill','stylers':[{'color':'#d59563'}]},{'featureType':'poi.park','elementType':'geometry','stylers':[{'color':'#263c3f'}]},{'featureType':'poi.park','elementType':'labels.text.fill','stylers':[{'color':'#6b9a76'}]},{'featureType':'road','elementType':'geometry','stylers':[{'color':'#38414e'}]},{'featureType':'road','elementType':'geometry.stroke','stylers':[{'color':'#212a37'}]},{'featureType':'road','elementType':'labels.text.fill','stylers':[{'color':'#9ca5b3'}]},{'featureType':'road.highway','elementType':'geometry','stylers':[{'color':'#746855'}]},{'featureType':'road.highway','elementType':'geometry.stroke','stylers':[{'color':'#1f2835'}]},{'featureType':'road.highway','elementType':'labels.text.fill','stylers':[{'color':'#f3d19c'}]},{'featureType':'transit','elementType':'geometry','stylers':[{'color':'#2f3948'}]},{'featureType':'transit.station','elementType':'labels.text.fill','stylers':[{'color':'#d59563'}]},{'featureType':'water','elementType':'geometry','stylers':[{'color':'#17263c'}]},{'featureType':'water','elementType':'labels.text.fill','stylers':[{'color':'#515c6d'}]},{'featureType':'water','elementType':'labels.text.stroke','stylers':[{'color':'#17263c'}]}]",
            urlStyle:
                '&style=element:geometry%7Ccolor:0x242f3e&style=element:labels.text.fill%7Ccolor:0x746855&style=element:labels.text.stroke%7Ccolor:0x242f3e&style=feature:administrative.locality%7Celement:labels.text.fill%7Ccolor:0xd59563&style=feature:poi%7Celement:labels.text.fill%7Ccolor:0xd59563&style=feature:poi.park%7Celement:geometry%7Ccolor:0x263c3f&style=feature:poi.park%7Celement:labels.text.fill%7Ccolor:0x6b9a76&style=feature:road%7Celement:geometry%7Ccolor:0x38414e&style=feature:road%7Celement:geometry.stroke%7Ccolor:0x212a37&style=feature:road%7Celement:labels.text.fill%7Ccolor:0x9ca5b3&style=feature:road.highway%7Celement:geometry%7Ccolor:0x746855&style=feature:road.highway%7Celement:geometry.stroke%7Ccolor:0x1f2835&style=feature:road.highway%7Celement:labels.text.fill%7Ccolor:0xf3d19c&style=feature:transit%7Celement:geometry%7Ccolor:0x2f3948&style=feature:transit.station%7Celement:labels.text.fill%7Ccolor:0xd59563&style=feature:water%7Celement:geometry%7Ccolor:0x17263c&style=feature:water%7Celement:labels.text.fill%7Ccolor:0x515c6d&style=feature:water%7Celement:labels.text.stroke%7Ccolor:0x17263c'
        },
        Aubergine: {
            id: 5,
            label: 'Aubergine',
            style:
                "[{'elementType':'geometry','stylers':[{'color':'#1d2c4d'}]},{'elementType':'labels.text.fill','stylers':[{'color':'#8ec3b9'}]},{'elementType':'labels.text.stroke','stylers':[{'color':'#1a3646'}]},{'featureType':'administrative.country','elementType':'geometry.stroke','stylers':[{'color':'#4b6878'}]},{'featureType':'administrative.land_parcel','elementType':'labels.text.fill','stylers':[{'color':'#64779e'}]},{'featureType':'administrative.province','elementType':'geometry.stroke','stylers':[{'color':'#4b6878'}]},{'featureType':'landscape.man_made','elementType':'geometry.stroke','stylers':[{'color':'#334e87'}]},{'featureType':'landscape.natural','elementType':'geometry','stylers':[{'color':'#023e58'}]},{'featureType':'poi','elementType':'geometry','stylers':[{'color':'#283d6a'}]},{'featureType':'poi','elementType':'labels.text.fill','stylers':[{'color':'#6f9ba5'}]},{'featureType':'poi','elementType':'labels.text.stroke','stylers':[{'color':'#1d2c4d'}]},{'featureType':'poi.park','elementType':'geometry.fill','stylers':[{'color':'#023e58'}]},{'featureType':'poi.park','elementType':'labels.text.fill','stylers':[{'color':'#3C7680'}]},{'featureType':'road','elementType':'geometry','stylers':[{'color':'#304a7d'}]},{'featureType':'road','elementType':'labels.text.fill','stylers':[{'color':'#98a5be'}]},{'featureType':'road','elementType':'labels.text.stroke','stylers':[{'color':'#1d2c4d'}]},{'featureType':'road.highway','elementType':'geometry','stylers':[{'color':'#2c6675'}]},{'featureType':'road.highway','elementType':'geometry.stroke','stylers':[{'color':'#255763'}]},{'featureType':'road.highway','elementType':'labels.text.fill','stylers':[{'color':'#b0d5ce'}]},{'featureType':'road.highway','elementType':'labels.text.stroke','stylers':[{'color':'#023e58'}]},{'featureType':'transit','elementType':'labels.text.fill','stylers':[{'color':'#98a5be'}]},{'featureType':'transit','elementType':'labels.text.stroke','stylers':[{'color':'#1d2c4d'}]},{'featureType':'transit.line','elementType':'geometry.fill','stylers':[{'color':'#283d6a'}]},{'featureType':'transit.station','elementType':'geometry','stylers':[{'color':'#3a4762'}]},{'featureType':'water','elementType':'geometry','stylers':[{'color':'#0e1626'}]},{'featureType':'water','elementType':'labels.text.fill','stylers':[{'color':'#4e6d70'}]}]",
            urlStyle:
                '&style=element:geometry%7Ccolor:0x1d2c4d&style=element:labels.text.fill%7Ccolor:0x8ec3b9&style=element:labels.text.stroke%7Ccolor:0x1a3646&style=feature:administrative.country%7Celement:geometry.stroke%7Ccolor:0x4b6878&style=feature:administrative.land_parcel%7Celement:labels.text.fill%7Ccolor:0x64779e&style=feature:administrative.province%7Celement:geometry.stroke%7Ccolor:0x4b6878&style=feature:landscape.man_made%7Celement:geometry.stroke%7Ccolor:0x334e87&style=feature:landscape.natural%7Celement:geometry%7Ccolor:0x023e58&style=feature:poi%7Celement:geometry%7Ccolor:0x283d6a&style=feature:poi%7Celement:labels.text.fill%7Ccolor:0x6f9ba5&style=feature:poi%7Celement:labels.text.stroke%7Ccolor:0x1d2c4d&style=feature:poi.park%7Celement:geometry.fill%7Ccolor:0x023e58&style=feature:poi.park%7Celement:labels.text.fill%7Ccolor:0x3C7680&style=feature:road%7Celement:geometry%7Ccolor:0x304a7d&style=feature:road%7Celement:labels.text.fill%7Ccolor:0x98a5be&style=feature:road%7Celement:labels.text.stroke%7Ccolor:0x1d2c4d&style=feature:road.highway%7Celement:geometry%7Ccolor:0x2c6675&style=feature:road.highway%7Celement:geometry.stroke%7Ccolor:0x255763&style=feature:road.highway%7Celement:labels.text.fill%7Ccolor:0xb0d5ce&style=feature:road.highway%7Celement:labels.text.stroke%7Ccolor:0x023e58&style=feature:transit%7Celement:labels.text.fill%7Ccolor:0x98a5be&style=feature:transit%7Celement:labels.text.stroke%7Ccolor:0x1d2c4d&style=feature:transit.line%7Celement:geometry.fill%7Ccolor:0x283d6a&style=feature:transit.station%7Celement:geometry%7Ccolor:0x3a4762&style=feature:water%7Celement:geometry%7Ccolor:0x0e1626&style=feature:water%7Celement:labels.text.fill%7Ccolor:0x4e6d70'
        }
    };

    export function GetStyleByStyleId(id: number): google.maps.MapTypeStyle[] {
        // Replace all double quotes to single quotes
        // eslint-disable-next-line @typescript-eslint/no-unused-vars
        const style = Style[OSFramework.Enum.OSMap.Style[id - 1]].style.replace(
            /'/g,
            '"'
        );
        // Parse to JSON and return the value
        return style !== '' ? JSON.parse(style) : '';
    }
}
