#
# This action creates a pull request using GitHub CLI.
# It is designed to work with branches that already have commits pushed to them.
#
# HOW TO USE:
#
# To call this reusable action, copy the code between === lines to workflow file,
# uncomment and adjust "uses" as needed (use the latest tag available).
# ======================================================================
# on:
#
#     (...)
#     steps:
#     (...)
#       - name: Create pull request
#         uses: ./.github/actions/create-pull-request
#         with:
#           token: ${{ steps.get-github-token.outputs.az-keyvault-value }}
#           base: dev
#           head: ${{ BRANCH_NAME }}
#           title: 'PR Title'
#           body: 'PR Description'
#
# ======================================================================
#

name: Create Pull Request
description: 'Creates a pull request using GitHub CLI from an existing branch'
inputs:
    token:
        description: 'GitHub token for authentication'
        required: true
        default: ''
    base:
        description: 'Base branch for the pull request'
        required: true
        default: ''
    head:
        description: 'Head branch (source branch) for the pull request'
        required: true
        default: ''
    title:
        description: 'Title of the pull request'
        required: true
        default: ''
    body:
        description: 'Body/description of the pull request'
        required: false
        default: ''

runs:
    using: composite
    steps:
        - name: Create pull request
          shell: bash
          env:
              GH_TOKEN: ${{ inputs.token }}
          run: |
              if [ -z "${{ inputs.body }}" ]; then
                  gh pr create \
                    --base ${{ inputs.base }} \
                    --head ${{ inputs.head }} \
                    --title "${{ inputs.title }}"
              else
                  # Use a here-doc to properly handle multi-line body text
                  gh pr create \
                    --base ${{ inputs.base }} \
                    --head ${{ inputs.head }} \
                    --title "${{ inputs.title }}" \
                    --body "${{ inputs.body }}"
              fi
