// eslint-disable-next-line @typescript-eslint/no-unused-vars
namespace OSFramework.Maps.Helper {
	/** Generates a new uniqueId based on the pseudorandom algorithm
	 * It is useful to create new uniqueIds for the new elements that are generated by drawing on the Map
	 */
	export function GenerateUniqueId(): string {
		return Math.random().toString(36);
	}
}
