# File: jobs/azure-pipelines-reactive.yml
parameters:

- name: currentBranch
  type: string
- name: sourceBranch
  type: string
  
stages: 
- stage: CheckBranch
  jobs:
    - job: CheckBranchJob
      displayName: 'Check Branch Exists'
      pool:
            vmImage: 'windows-latest'
      steps:    
      #Format branch name
      - bash: |
            declare BRANCH 
            BRANCH=$(system.pullRequest.sourceBranch)
            echo "Map_Regressions_${BRANCH//[-]/}"
            echo "##vso[task.setvariable variable=branch;]Map_Regressions_${BRANCH//[-]/}"
            echo "##vso[task.setvariable variable=module;isoutput=true]Map_Regressions_${BRANCH//[-]/}"
        name: branch_name

      #Ping sample test page
      #Sets skip variable as true if sample doesnt exist.
      - bash: |
          status=$(curl -s --head -w %{http_code} $(ENV_URL)/$(branch)/ -o /dev/null)
          echo $status
          echo $(ENV_URL)/$(branch)/
          if [[ $status = 404 ]]
          then
            echo "##vso[task.setvariable variable=skip;isoutput=true]true"
          fi
        displayName: "Ping sample test page"
        name: "skipTests"


- stage: Tests
  #Only run tests if not in dev branch
  condition: and(ne(stageDependencies.CheckBranch.outputs['CheckBranchJob.skipTests.skip'], 'true'), ne(variables['Build.SourceBranchName'], 'dev'), succeeded())
  displayName: 'Tests'
  variables:
    - group: "Services Credentials"
  
  jobs:
  - job: Run_Tests
    displayName: 'Run tests'
    timeoutInMinutes: 180
    variables:
      module: $[ stageDependencies.CheckBranch.CheckBranchJob.outputs['branch_name.module'] ]
    pool:
          vmImage: 'windows-latest'
    steps:   
    - checkout: outsystems-maps-tests 
    - template: './azure/azure-pipelines-template.yml@outsystems-maps-tests'
      parameters:
        module: $(module)
        browser: Chrome
        environment: dev
        instances: 2
