name: CI
on:
    # Triggers the workflow on push events but only for the "dev" branch.
    push:
        branches: ['dev']

jobs:
    build:
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - name: Checkout branch dev
              uses: actions/checkout@v3
              with:
                  ref: dev
                  token: ${{ secrets.PAT }}

            - name: Install graphviz
              run: sudo apt install -y graphviz

            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: 'npm'

            - name: Install project dependencies
              run: npm install

            - name: Generate documentation
              run: npm run docs

            - name: Sign and commit documentation to branch dev
              uses: ./.github/signed-commit/
              with:
                  branch: dev
                  message: 'Update documentation [skip ci]'
                  newFiles: true
                  gpgPriv: ${{ secrets.GPG_SIGN_KEY }}
                  gpgPassPhrase: ${{ secrets.GPG_PASSPHRASE }}
