name: PullRequest into Dev branch
on:
    # Triggers the workflow on push events but only for the "dev" branch.
    pull_request:
        branches: ['dev']

jobs:
    eslint:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./
        steps:
            - name: Checkout branch dev
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

            - name: Install project dependencies
              run: npm install

            - name: Run lint
              run: npm run lint

    compile-code:
        needs: eslint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout branch dev
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

            - name: Install project dependencies
              run: npm install

            - name: Compile code
              run: npm run build
